name: ANDROID BUILD KERNEL

on:
  push:
  schedule:
    - cron: '* * * * *'

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Setup
      run: |
        sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
        sudo apt-get update
        sudo apt-get install -y git wget
    - name: Clone Repository
      run: |
        git clone https://github.com/Baka-Project/Baka-Msm-4.4
    - name : Go To Dir
      run: |
        cd Baka-Msm-4.14
    - name: Get Script Building
      run: |
        wget https://raw.githubusercontent.com/vcyzteen/myscripts/master/MASTER.sh
    - name: Starting
      run: |
        bash MASTER.sh
